"""Run-level lifecycle contracts for agent invocation records.

These models capture the identity, timing, and outcome of a single agent
graph execution. They are intentionally separate from ``RuntimeRequest`` and
``RuntimeResponse``:

- ``RuntimeRequest`` / ``RuntimeResponse`` model the API boundary.
- ``AgentRun`` models the internal execution lifecycle record.

``AgentRun`` is not persisted in PR-007. The model exists now so the shape of
a run record is an explicit, typed contract before persistence, streaming, or
observability integrations are introduced. Future PRs can store ``AgentRun``
without changing the fields that downstream callers already depend on.

Relationship between identifiers:
- ``thread_id``: stable conversation key supplied by the caller; persists
  across multiple turns of the same conversation.
- ``request_id``: identifies one HTTP request; generated by middleware if not
  provided by the caller via ``X-Request-ID``; scoped to a single HTTP call.
- ``run_id``: identifies one agent graph execution; generated inside the
  invocation service; strictly narrower than a request (future requests may
  trigger multiple runs per HTTP call once fan-out is introduced).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from snp_agent_core.contracts.status import AgentRunStatus


class AgentRunTiming(BaseModel):
    """Execution timing captured around a single agent graph invocation.

    ``total_ms`` is the wall-clock duration from the moment graph execution
    started to the moment the graph returned, measured in whole milliseconds.
    ``None`` means timing was not captured (e.g. the run failed before the
    graph was reached).
    """

    model_config = ConfigDict(extra="forbid")

    total_ms: int | None = Field(
        default=None,
        ge=0,
        description="Wall-clock graph execution duration in milliseconds.",
    )


class AgentRunError(BaseModel):
    """Structured error information attached to a failed agent run.

    ``code`` is a stable machine-readable error identifier safe to expose to
    clients and logging pipelines. ``message`` is a human-readable description
    of the failure. ``retryable`` advises whether the caller may safely retry
    the same request without a change in inputs or configuration.
    """

    model_config = ConfigDict(extra="forbid")

    code: str = Field(..., description="Stable machine-readable error code.")
    message: str = Field(..., description="Human-readable failure description.")
    retryable: bool = Field(
        default=False,
        description="Whether the caller may safely retry this request.",
    )

    @field_validator("code", "message")
    @classmethod
    def reject_blank_strings(cls, value: str) -> str:
        """Reject blank error fields before they enter logs or client responses."""

        stripped = value.strip()
        if not stripped:
            raise ValueError("field must not be blank")
        return stripped


class AgentRun(BaseModel):
    """Lifecycle record for a single agent graph invocation.

    ``AgentRun`` is the authoritative record of what happened during one
    execution: who requested it, which agent ran, when it started and ended,
    whether it succeeded, and any timing or error detail.

    This model is designed to be persisted in a future PR. The fields are
    intentionally flat and domain-neutral so the record is reusable across
    storage backends (SQL, document stores, event streams) without schema
    negotiation.

    Lifecycle state machine:
      COMPLETED    — graph ran to the end node and returned a final answer.
      FAILED       — graph raised an exception or returned an error state.
      INTERRUPTED  — graph was halted before completing (e.g. safety halt).
      REQUIRES_*   — graph is waiting for external approval or human input.
    """

    model_config = ConfigDict(extra="forbid")

    run_id: str = Field(..., description="Platform-generated unique run identifier.")
    request_id: str = Field(
        ...,
        description="HTTP request identifier from which this run was triggered.",
    )
    agent_id: str = Field(..., description="Stable agent identifier from the manifest.")
    agent_version: str = Field(..., description="Agent behavior version at execution time.")
    tenant_id: str = Field(..., description="Tenant routing identifier.")
    channel: str = Field(..., description="Ingress channel, e.g. api, zalo, web.")
    user_id: str = Field(..., description="Stable user identifier within the tenant.")
    thread_id: str = Field(..., description="Conversation thread identifier.")
    status: AgentRunStatus = Field(..., description="Terminal or paused execution outcome.")
    started_at: datetime = Field(..., description="UTC timestamp when graph execution started.")
    completed_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when graph execution ended; None if not yet complete.",
    )
    timing: AgentRunTiming | None = Field(
        default=None,
        description="Execution timing captured around graph invocation.",
    )
    error: AgentRunError | None = Field(
        default=None,
        description="Structured error detail present when status indicates failure.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Serializable run-level metadata for tracing and audit pipelines.",
    )

    @field_validator("run_id", "request_id", "agent_id", "agent_version",
                     "tenant_id", "channel", "user_id", "thread_id")
    @classmethod
    def reject_blank_required_strings(cls, value: str) -> str:
        """Reject blank identity fields before the record enters any pipeline."""

        stripped = value.strip()
        if not stripped:
            raise ValueError("field must not be blank")
        return stripped
